### ISSUE TITLE
401 when registering 

### ISSUE THREAD

**Issue by KeithTAllen** [PavlAvstin/OZ-CSC-480-HCI-521-Fall-2023-#130]
When trying to register, I am being returned a 401 register error. I have attached a text version of the output. 
CURL
<code>curl -X 'POST' \
  'http://localhost:30500/reel-rating-auth-service/auth/register' \
  -H 'accept: */*' \
  -H 'Content-Type: application/json' \
  -d '{
  "username": "string",
  "password": "string12!",
  "email": "string@gmail.com"
}'</code>
Request URL
<code>http://localhost:30500/reel-rating-auth-service/auth/register</code>

Error 401 unauthorized 

Response headers 
<code>connection: keep-alive 
 content-language: en 
 content-length: 0 
 date: Tue,31 Oct 2023 15:01:07 GMT 
 server: nginx/1.25.3 </code>

**Comment by DeveloperDave17** [comment]
#132 solves this issue. I forgot to link it upon committing
