### ISSUE TITLE
/movie/getRecentReleaseMovies

### ISSUE THREAD

**Issue by Mackenzie-rae** [PavlAvstin/OZ-CSC-480-HCI-521-Fall-2023-#135]
Instead of returning recently released movies, I get a 500 code error. 

connection: keep-alive 
 content-language: en 
 content-length: 0 
 date: Tue,31 Oct 2023 21:58:34 GMT 
 io.openliberty.restfulws.mpmetrics.metricsrestfulwsemcallbackimpl.exception: java.lang.NullPointerException: Cannot invoke "org.bson.Document.getString(Object)" because "ratingNameDoc" is null 
 server: nginx/1.25.3

**Comment by KeithTAllen** [comment]
ratingNameDoc is within the getMostPopularAggregatedRatingForMovie method in the movie data service. It seems that the movie that we are looking for is returning null. Either the Id we are looking with is busted or something else that I cannot think of is not working.

**Comment by DeveloperDave17** [comment]
This issue is being cause by a new movie with a recent release date being added to the database. The endpoint is running into a null exception because the added movie doesn't have any ratings yet.
