### ISSUE TITLE
Unable to Create Ratings and Icons Not Functional

### ISSUE THREAD

**Issue by pez-man** [PavlAvstin/OZ-CSC-480-HCI-521-Fall-2023-#166]
**Problem 1**: Unable to Create Ratings
I've encountered an issue while trying to create new ratings on the movie rating web application. Here are the steps I followed:

Added a name to the rating - Successful.
Set the scale from start to end - Successful.
Attempted to make the rating clear - Unsuccessful.
Upon trying to make the rating clear, it seems that this functionality is not working as expected. The system doesn't respond appropriately, and the clarity of the rating is not updated.

**Problem 2**: Non-functional Icons
Additionally, I noticed that the "create rating" icon and the public icon are not functional. Clicking on these icons does not trigger any action.

**Steps to Reproduce:**

Log in to the application.
Navigate to the rating creation section.
Follow the steps for creating a new rating.
Observe the issues with making the rating clear and the non-functional icons.

**Expected Behavior**:

The rating should be successfully created with clear functionality.
The "**create rating**" and **public** icons should trigger their respective actions.

**Environment**:

Operating System: Mac OS
Browser: Chrome

Thank you!

**Comment by KeithTAllen** [comment]
This is about the `clear` button on the rating modal not removing any already input text.

**Comment by pez-man** [comment]
You mean it will just clear the text, or it will reset the rating?
