### ISSUE TITLE
Submitting a rating and how it updates issue

### ISSUE THREAD

**Issue by Mackenzie-rae** [PavlAvstin/OZ-CSC-480-HCI-521-Fall-2023-#194]
As of right now when creating a rating and then trying to update it by creating a second rating it will throw out the second rating and keep your initial rating. Instead it should update the first rating with the second ratings information, instead of throwing it out.

**Comment by pez-man** [comment]
This issue should get an update, so I will close it and make a new one.

**Comment by pez-man** [comment]
I have updated this issue in a new one, I dont have the close issue here, I think @Mackenzie-rae should close it.
