### ISSUE TITLE
Clear button not working

### ISSUE THREAD

**Issue by Mackenzie-rae** [PavlAvstin/OZ-CSC-480-HCI-521-Fall-2023-#195]
There are 4 instances on the rating modal where the clear button does not work.

**Comment by DeveloperDave17** [comment]
As of pull request #203 this should be resolved for everything but the up/down rating area that needs to be reworked.

**Comment by Mackenzie-rae** [comment]
Correct all clear buttons are now working except for the up/down rating area that needs to be reworked.
